Testtuple = ("This", "is", "a", "test", "Tuple","42","60")
print(Testtuple)
print(f"{int(Testtuple[5]) + int(Testtuple[6])}")
NTup = (42, 24)
print(sum(NTup))
print(f"The total of the tuple is {sum(NTup)}")
